### ISSUE TITLE
Allow using Craft Config from merge target branch 

### ISSUE THREAD

**Issue by Lms24** [getsentry/publish#3441]
## Motivation:

We run into situations where we need to backport fixes or features to older SDK/tool major versions or where we publish or stop publishing artifacts in major versions. Examples:

- Sentry CLI v1/v2
- Sentry JavaScript v7 once we publish v8
  - Considering there are numerous fundamental changes from v7 to v8, we expect to maintain/backport changes to v7 for quite some time after the v8 release.
- Potentially more SDKs

## Problem:

- Craft Config (`.craft.yml`) is currently always taken from the repo's default branch
- Release artifacts vary between major versions
    - artifacts removed
    - artifacts added
- ⇒ Craft config diverges (and it should)
    - We want to have strict checks of artifact presence, for each major version
    - Config on the default branch causes conflicts with older version
    - Example:
        - v2 of Sentry CLI requires artifacts that are not present in v1
        - v8 of JS SDK removes packages that should be present in v7

## Solution: Take config from merge target branch

_(This solution was discussed and accepted internally prior to writing this issue)_

The merge target branch can be configured in the "Prepare Release" Action. 

We'll protect the merge target branch to disallow direct commits/merges w/o approval.
Furthermore, we add a new input option to the "Prepare Release" action so that individual repos can opt into this new behaviour.

**Pros:**
- Allows config diversion
- Compliance issue alleviated:
    - Changes merged into target must be peer-reviewed

**Cons:**
- Still kinda unexpected/obscure (as opposed to taking the config from the release branch) if you’re not familiar with this detail in the publishing flow. However, this is approach is safer because release branches are not protected and one actor alone could make changes to the publishing process without a review.

## Implementation

```[tasklist]
### Prepare Release Action
- [ ] https://github.com/getsentry/action-prepare-release/pull/34
- [ ] https://github.com/getsentry/action-prepare-release/pull/35
- [ ] https://github.com/getsentry/action-prepare-release/pull/36
```

```[tasklist]
### Publish repo `publish.yml` workflow
- [ ] https://github.com/getsentry/publish/pull/3451
- [ ] https://github.com/getsentry/publish/pull/3452
- [ ] https://github.com/getsentry/publish/pull/3455
```

## Example Usage in Sentry JS:

These PRs were necessary to opt into the new process

1. https://github.com/getsentry/sentry-javascript/pull/10763
2. https://github.com/getsentry/publish/pull/3467

**Comment by BYK** [comment]
I think this issue needs the "enhancement" tag to make it stand out from publish requests.

**Comment by Lms24** [comment]
Would love to add labels/assignments but I can't change any fields there ;)

**Comment by BYK** [comment]
>Would love to add labels/assignments but I can't change any fields there ;)

That's by design so maybe @HazAT can help wiwth that :)

**Comment by Lms24** [comment]
Closing this as completed.
