### ISSUE TITLE
release-bot isn't enough: getsentry-release is required

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/publish#808]
> Make sure you don't have branch protections enabled on your repository or the [release-bot team](https://github.com/orgs/getsentry/teams/release-bot) is added to your repository as an admin with the "Include administrators" option disabled.

Adding only the release-bot group as admin isn't working. We need to add getsentry-release as admin to the repo.

![image](https://user-images.githubusercontent.com/1633368/153439999-ccf8fc52-3c24-4455-ac06-ad495d5a6e99.png)

**Comment by jan-auer** [comment]
@bruno-garcia I was recently able to publish `getsentry/rust-debugid` successfully with just the `release-bot` team permissions. Can you share slightly more context in which step this is failing?

**Comment by bruno-garcia** [comment]
not sure why it failed, just closing it
