### ISSUE TITLE
Leave a comment if CI on the release branch fails

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/publish#834]
If CI on the release branch fails, the package won’t be able to be published. In most cases, it’s a flake, so it just needs to be re-rerun. It would be helpful if the bot could leave a comment in the publish issue every time the CI fails on the release branch, and point users to either remake the branch, re-run CI or fix the tests.

**Comment by kamilogorek** [comment]
I played around with it, and at the time of failure, complete logs are not available yet, thus we don't have an easy access to them :(

**Comment by AbhiPrasad** [comment]
IMO even just a simple comment is a good start - like hey look at the check runs as there is something wrong.

**Comment by kamilogorek** [comment]
How is that any different from what we have now? When it fails, the comment says:

```
Failed to publish. ([error logs](https://github.com/getsentry/publish/actions/runs/2029660149?check_suite_focus=true#step:8))

Bad branch? You can [delete with ease](https://github.com/getsentry/sentry-java/branches/all?query=6.0.0-alpha.4) and start over.
```

And then when you click on it, the logs say:

> Build(s) for revision 4f8b0ef679a7f06233e8685abe4ed7af60b104b4 have not succeeded. Please check the revision's status.

**Comment by kamilogorek** [comment]
Without `accepted`, there is no action in progress, so we'd have to somehow pool it using cron, which would go through every open issue and get it's related repo status. I don't think its feasible tbh  :3

**Comment by AbhiPrasad** [comment]
Fair, I'll close for now then, thanks for taking a look!
